// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/MuxiKeStack/be-collect/grpc"
	"github.com/MuxiKeStack/be-collect/ioc"
	"github.com/MuxiKeStack/be-collect/pkg/grpcx"
	"github.com/MuxiKeStack/be-collect/repository"
	"github.com/MuxiKeStack/be-collect/repository/dao"
	"github.com/MuxiKeStack/be-collect/service"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	collectDAO := dao.NewGORMCollectDAO(db)
	collectRepository := repository.NewCollectRepository(collectDAO)
	collectService := service.NewCollectService(collectRepository)
	collectServiceServer := grpc.NewCollectServiceServer(collectService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxKratosServer(collectServiceServer, client, logger)
	return server
}
